# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoportailLU
                                 A QGIS plugin
 Use services from the luxembourgish Geoportal in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-04-20
        copyright            : (C) 2018 by Dipl. Geogr. Frank Broniewski
        email                : hallo@frankbroniewski.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoportailLU class from file GeoportailLU.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geoportail_lu import GeoportailLU
    return GeoportailLU(iface)
